__author__ = 'aknay'
WIRELESS_STARTING_BYTE = chr(0xf8)
GET_TARED_QUAT = chr(0x00)
GET_STREAMING_TIMING = chr(0x53)
START_STREAMING = chr(0x55)
STOP_STREAMING = chr(0x56)
SET_STREAMING_TIMING = chr(0x52)
